name: generate domains index

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v6

      - name: setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: install deps
        run: pnpm install

      - name: run
        run: node src/index.ts

      - name: create release
        run: |
          TAG=$(date +'%Y-%m-%d-%H%M%S')
          gh release create "$TAG" domains.json.gz --title "is-a.dev on $TAG" --notes "meow ig"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
